<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>005_1024.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\jxl.net\jxlNET.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="example\160011_architecture-air-conditioner-building.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Out\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="005_1024.ico" />
    <Resource Include="005_1024.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-HDRI-OpenMP-x64" Version="14.10.4" />
    <PackageReference Include="Magick.NET.Core" Version="14.10.4" />
    <PackageReference Include="Magick.NET.SystemDrawing" Version="8.0.17" />
    <PackageReference Include="Magick.NET.SystemWindowsMedia" Version="8.0.17" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
  </ItemGroup>
</Project>