name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore nuget dependencies
      run: nuget restore jxlNET.sln
    - name: Build
      run: msbuild /p:Configuration=Release
    
    # Upload the artifacts: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts jxl.net
      uses: actions/upload-artifact@v3
      with:
        name: jxl.net
        path: jxl.net\bin\x64\Release
    - name: Upload build artifacts jxlViewer
      uses: actions/upload-artifact@v3
      with:
        name: jxlViewer
        path: jxlViewer\bin\x64\Release
    - name: Upload build artifacts WpfExample
      uses: actions/upload-artifact@v3
      with:
        name: WpfExample
        path: WpfExample\bin\x64\Release
