name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "10.0.x"

    - name: Publish single-file
      run: dotnet publish ./WpfExampleCore/WpfExampleCore.csproj -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=false -p:EnableCompressionInSingleFile=true -f net10.0-windows -p:AllowUnsafeBlocks=true

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Zip publish folder
      run: Compress-Archive -Path "WpfExampleCore\bin\Release\net10.0-windows\win-x64\publish\*" `
                            -DestinationPath "WpfExampleCore.zip"
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: WpfExampleCore.zip
        asset_name: WpfExampleCore.zip
        asset_content_type: application/zip
